### ISSUE TITLE
Address is not added to customer addresses

### ISSUE THREAD

**Issue by eirabben** [elleracompany/commerce-klarna-checkout#30] opened 2020-03-20 09:07 UTC
When a customer checks out with an address for the first time, the address used is set as primary billing address, but not saved into the customer's addresses in commerce.

This leads to the customer not being able to change the address from the frontend. A workaround here is to check if the address is in the customer's addresses, and treat it as a new address if it isn't. After saving another address as primary, the Klarna checkout will use this, but it won't be updated if the customer changes things in the Klarna window at checkout.

**Comment by jellingsen** [comment] 2020-05-04 10:56
I am unable to reproduce. Can you confirm that the issue is still present in the latest release of Craft Commerce?

If it is still present, could you provide a more detailed explanation on how to reproduce the issue?

**Comment by jellingsen** [comment] 2020-05-22 06:57
Closing this now. If this issue is still present please reopen or create a new issue.

**Closed by jellingsen** 2020-05-22 06:57 UTC
Labels: bug
